### PR TITLE
Use bufio.Reader and io.ReadFull

### PR DESCRIPTION
**Pull request by jgraettinger**
Custom read batching allocated heavily. Remove it, and use io.ReadFull
instead. Wrap network connections in a bufio.Reader as a more efficient
(and non-allocating!) mitigation for small reads.

Also, set the default Logger level to WARN, and make a scary looking
log statement warning-level.

---
This change is [Reviewable](https://reviewable.io/reviews/arbortech/aerospike-client-go/3)

### CODE REVIEW

**Comment by mharris717** [comment]
Done

---

Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[batch_command.go, line 161 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrkwbptdPHsUE8oe64:-KNrkwbptdPHsUE8oe65:-2095536230) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/batch_command.go#L161)):*
> ```Go
> 	}
> 
> 	var n, err = io.ReadFull(cmd.conn.conn, cmd.dataBuffer[:length])
> ```

Should this be calling cmd.conn.Read?

---

*[batch_command_get.go, line 110 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrkFM-q9mia14gBJEz:-KNrkFM-q9mia14gBJF-:-1416102186) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/batch_command_get.go#L110)):*
> ```Go
> 		} else {
> 			Logger.Warn("Unexpected batch key returned: ns %s d %x g %v e %v fcnt %v opcnt %v",
> 				key.namespace, key.digest, generation, expiration, fieldCount, opCount)
> ```

Assume no value to Buffer.BytesToHexString(key.digest) instead of key.digest here

---

*[connection.go, line 38 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrhRFqzz1wUGcwpn_G:-KNrhRFqzz1wUGcwpn_H:-47646841) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/connection.go#L38)):*
> ```Go
> 	// connection object
> 	conn    *bufio.Reader
> 	rawconn net.Conn
> ```

rawConn (capitalization)? Does conn make more sense as readConn? rawconn could then stay rawconn or just be conn. 

---

*[connection.go, line 65 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrjZAlEocEeRTNrf8i:-KNrjZAm4Ah3Q69nTiAC:607429961) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/connection.go#L65)):*
> ```Go
> 		t.SetKeepAlivePeriod(5 * time.Second)
> 	}
> 	newConn.conn = bufio.NewReader(newConn.rawconn)
> ```

I assume no large performance hit to doing this here instead of lazily and/or we'll never not be reading.

---

*[logger/logger.go, line 51 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrjqWWSGdplrxrC8nM:-KNrjqWWSGdplrxrC8nN:210617706) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/4e08e134ea61f93f2ab4797d79c38581fafdaa6e/logger/logger.go#L51)):*
> ```Go
> 	return &logger{
> 		Logger: log.New(os.Stdout, "", log.LstdFlags),
> 		level:  OFF,
> ```

I have no idea about this. Assume that you do obviously, so I'll rubber stamp it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-:-KNrlRWKHTOpV8m39ilb:676635175)*

**Comment by joshk0** [comment]
drive-by comments

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[batch_command_get.go, line 110 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrkFM-q9mia14gBJEz:-KNs5zc2zT_U5wJrkxsi:2064324513) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/batch_command_get.go#L110)):*
<details><summary><i>Previously, mharris717 (Mike Harris) wrote…</i></summary>
> Assume no value to Buffer.BytesToHexString(key.digest) instead of key.digest here
</details>
%x already does the hex-string conversion.

---

*[logger/logger.go, line 51 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrjqWWSGdplrxrC8nM:-KNs5NoiA_VImd9mNsVP:1085313582) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/4e08e134ea61f93f2ab4797d79c38581fafdaa6e/logger/logger.go#L51)):*
<details><summary><i>Previously, mharris717 (Mike Harris) wrote…</i></summary>
> I have no idea about this. Assume that you do obviously, so I'll rubber stamp it. 
</details>
The biggest problem is that this doesn't go through logrus. It would be ideal if a client hook would let us run aerospike messages through logrus?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-:-KNs64T6el85fXdEXXN_:163792245)*

**Comment by jgraettinger** [comment]
Thanks, PTAL.

---

Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[batch_command.go, line 161 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrkwbptdPHsUE8oe64:-KO19u4ZBFF9L6V1jYoU:-1324139440) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/batch_command.go#L161)):*
<details><summary><i>Previously, mharris717 (Mike Harris) wrote…</i></summary>
> Should this be calling cmd.conn.Read?
</details>
I didn't want to add further dependence on the wacky `cmd.conn.Read`. Re-purposing canonical standard library interface signatures is a Bad Idea. Added a TODO on `Read`.

---

*[connection.go, line 38 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrhRFqzz1wUGcwpn_G:-KO1AwoQR2qzDU6mhpvN:-1155850106) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/connection.go#L38)):*
<details><summary><i>Previously, mharris717 (Mike Harris) wrote…</i></summary>
> rawConn (capitalization)? Does conn make more sense as readConn? rawconn could then stay rawconn or just be conn. 
</details>
moved `rawconn` back to `conn` (name change was initially to force compiler errors / root out usages).

`conn` is now `reader`.

---

*[connection.go, line 65 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrjZAlEocEeRTNrf8i:-KO1CipMVScWWxL1VoHG:-209202849) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/connection.go#L65)):*
<details><summary><i>Previously, mharris717 (Mike Harris) wrote…</i></summary>
> I assume no large performance hit to doing this here instead of lazily and/or we'll never not be reading.
</details>
Correct. Best to not be lazy unless a profiler tells you too.

---

*[logger/logger.go, line 51 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrjqWWSGdplrxrC8nM:-KO1DZVeD7-WXlarDmvT:920394755) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/4e08e134ea61f93f2ab4797d79c38581fafdaa6e/logger/logger.go#L51)):*
<details><summary><i>Previously, joshk0 (Joshua Kwan) wrote…</i></summary>
> The biggest problem is that this doesn't go through logrus. It would be ideal if a client hook would let us run aerospike messages through logrus?
</details>
I think we can call `aero.Logger.SetLogger(logrusLogger)` from our code. In the mean time, these should be surfaced regardless of their log format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-:-KO1H6pYmajnh0hxOkup:1438382077)*

**Comment by mharris717** [comment]
Reviewed 3 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[batch_command.go, line 161 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrkwbptdPHsUE8oe64:-KO5OJRJMjB4YcOGfD8Z:872545031) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/batch_command.go#L161)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary>
> I didn't want to add further dependence on the wacky `cmd.conn.Read`. Re-purposing canonical standard library interface signatures is a Bad Idea. Added a TODO on `Read`.
</details>
Ok. I don't understand this in general, but assume the specifics make it make sense

---

*[connection.go, line 38 \[r1\]](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-KNrhRFqzz1wUGcwpn_G:-KO5OXGf-favN1WLhvvf:-485063445) ([raw file](https://github.com/arbortech/aerospike-client-go/blob/8065109d319c97fb41cb007f644b2ddfd3dd54e7/connection.go#L38)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary>
> moved `rawconn` back to `conn` (name change was initially to force compiler errors / root out usages).
> 
> `conn` is now `reader`.
</details>
Sweet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3)*

**Comment by mharris717** [comment]
:LGTM:

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3#-:-KO5OyOMLksg5hrvhggb:1386550993)*

**Comment by mharris717** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/aerospike-client-go/3)*

**Pull request merged**
